### ISSUE TITLE
[FEATURE] build functions to get and update repo task status in todo file

### ISSUE THREAD

**Issue by FlicAnderson** [FlicAnderson/RSE-personas#50]
**Brief task description:**  - *What needs to be done for this task/feature*    
  - [ ] be able to update task_name column for repo_name with status plus timestamp  
  - [ ] be able to read status of repo_name for task_name  
  - [ ] have a test to confirm it updates correctly  
 
**Does it relate to any other work / issues:** - *Not Yet*   

**Why is it needed?** - *Justification details for why this will be time well-spent and how it progresses my project work.*   
This will be important in building the larger system architecture for the coding-smart research workflow.   
Updating the todo file will avoid repeated API calls to get data that's already there.  
It should help identify problems in specific repos / particular edge case examples.  
This can be used in later scripts to mark tasks as 'completed' and help indicate progress in larger workflow operations.  
Adds reproducibility/traceability info about what was run when.  

**How should it be done?** - *Give a rough idea here, follow up with more details in further tickets as needed.*    
Create function (`utilities/` or `githubanalysis/processing`?).  

PSEUDOCODE:  
def status_getter(repo_name, task_name, todofile): 
    (check todofile exists)  
    (check repo_name in todofile)  
    (check task_name exists as column)  

   read todofile as df    
   variable = df[repo_name, task_name]
   (log?)
   return variable

def status_updater(repo_name, task_name, status, todofile): 
    (check todofile exists)  
    (check status in expected statuses)
    (check repo_name in todofile)  
    (check task_name exists as column)  

   read todofile as df    
   generate timestamp
   status_string = f"{status} @ {timestamp}"
   df[repo_name, task_name] = status_string
   overwrite/edit todofile with df 
   log status updated.

**Is your feature request related to a problem? Please describe.**
Currently todofile is only useful as an input file for gather_gh_stats.py; doesn't hold any statuses or explain what has been done.  

**Describe alternatives you've considered**
I could NOT have a todofile or status system, but this might require lots of re-runs to regenerate datasets where I've already gathered that data.  Maybe this is overkill amounts of detail, but it would help me keep track of how much data I have vs need easier.  

** How will I know when it's done?** - *When should this task/feature be considered 'finished'?*    
When I can get the current `status` of a `repo_name` from a specific `todofile`  
When I can update the status in a `todofile` for a `repo_name` for a `task_name` to `status`. 
When I can confirm this is working correctly.  

**Any other details of relevance?** - *Extra info, relevant links, prioritisation discussion etc.*
